import type { ListingCreate } from '@swapcircle/contracts';

export const members = [
  {
    key: 'guest',
    name: 'Camille Demo',
    location: 'Paris · 11th arrondissement',
    bio: 'A curious neighbour trading useful things for a little more space. Into weekend photography, books, and keeping balcony plants happy. This is the shared demo account.',
    interests: ['Books', 'Gardening', 'Outdoors', 'Repair'],
  },
  {
    key: 'lea',
    name: 'Léa Martin',
    location: 'Paris · 12th arrondissement',
    bio: 'Ceramics, windowsill plants, and slow Sunday cooking. Happy to give well-loved things another chapter. Fictional demo profile.',
    interests: ['Gardening', 'Books', 'Cooking'],
  },
  {
    key: 'noah',
    name: 'Noah Bernard',
    location: 'Paris · 10th arrondissement',
    bio: 'Always carrying a camera. Learning film photography and looking for equipment someone else will enjoy using. Fictional demo profile.',
    interests: ['Outdoors', 'Repair'],
  },
  {
    key: 'ines',
    name: 'Inès Laurent',
    location: 'Paris · 20th arrondissement',
    bio: 'Board-game evenings and cycling around the neighbourhood. I like objects with a story and games with all their pieces. Fictional demo profile.',
    interests: ['Books', 'Outdoors'],
  },
  {
    key: 'hugo',
    name: 'Hugo Petit',
    location: 'Paris · 18th arrondissement',
    bio: 'Making a small apartment feel like home. Into restoring furniture, cosy lighting, and sharing rather than buying twice. Fictional demo profile.',
    interests: ['Repair', 'Cooking'],
  },
  {
    key: 'sarah',
    name: 'Sarah Dubois',
    location: 'Paris · 9th arrondissement',
    bio: 'A wardrobe refresh without the shopping spree. Enjoys music, design, and long walks with a good podcast. Fictional demo profile.',
    interests: ['Music', 'Outdoors'],
  },
  {
    key: 'adam',
    name: 'Adam Moreau',
    location: 'Paris · 19th arrondissement',
    bio: 'Running routes along the canal and finding practical gear a new owner. Carefully described items, friendly swaps. Fictional demo profile.',
    interests: ['Outdoors', 'Repair'],
  },
  {
    key: 'maya',
    name: 'Maya Robert',
    location: 'Paris · 13th arrondissement',
    bio: 'Weekend trails and handwritten travel journals. Trading things I no longer reach for, keeping the memories. Fictional demo profile.',
    interests: ['Outdoors', 'Books'],
  },
  {
    key: 'eli',
    name: 'Éli Richard',
    location: 'Paris · 5th arrondissement',
    bio: 'Poetry, second-hand bookshops, and an ever-growing reading list. A book is happiest when it keeps moving. Fictional demo profile.',
    interests: ['Books', 'Music'],
  },
  {
    key: 'zoe',
    name: 'Zoé Simon',
    location: 'Paris · 14th arrondissement',
    bio: 'Vinyl on the turntable, a tidy desk, and a new project on the go. Interested in music and useful technology. Fictional demo profile.',
    interests: ['Music', 'Repair'],
  },
] as const;

export type MemberKey = (typeof members)[number]['key'];
export type DemoListing = ListingCreate & {
  key: string;
  owner: MemberKey;
  images: string[];
};

const item = (
  key: string,
  owner: MemberKey,
  title: string,
  description: string,
  images = [key],
  condition: ListingCreate['condition'] = 'good',
): DemoListing => ({
  key,
  owner,
  title,
  description: `${description}\n\nFictional demo listing; photographs are illustrative. No real exchange is offered.`,
  condition,
  images,
});

export const listings: DemoListing[] = [
  item(
    'backpack',
    'guest',
    'Everyday navy backpack',
    'A compact daypack with a front pocket and comfortable straps. Clean lining, light wear on the base. Ideal for carrying a book and a camera.',
  ),
  item(
    'camera',
    'guest',
    'Camera starter kit',
    'Camera and zoom lens for learning photography. All shown equipment is included in this fictional kit; happy to discuss a swap for another creative hobby.',
    ['camera', 'lens'],
  ),
  item(
    'books',
    'guest',
    'A little library to share',
    'A mixed bundle of well-loved books. Some marked pages and worn corners, plenty of reading left. Offered together as one bundle.',
    ['books', 'vintagebooks'],
    'fair',
  ),
  item(
    'cactus',
    'guest',
    'Sunny windowsill cactus',
    'A small cactus in its terracotta pot. Easy to care for with a sunny spot and occasional watering.',
  ),
  item(
    'bicycle',
    'guest',
    'City bicycle',
    'A simple city bike for relaxed neighbourhood rides. Used condition; inspect brakes and tyres before any real-world ride. This is a fictional demo item.',
    ['bicycle'],
    'fair',
  ),
  item(
    'guitar',
    'guest',
    'Acoustic guitar for quiet evenings',
    'An acoustic guitar with a warm wooden finish. Light signs of use; a good companion for learning a few favourite songs.',
  ),
  item(
    'headphones',
    'guest',
    'Over-ear headphones',
    'Comfortable black headphones for a desk or a long journey. Ear cushions are clean and the headband has normal signs of use.',
  ),
  item(
    'chair',
    'guest',
    'Soft grey accent chair',
    'A compact upholstered chair with wooden legs. A pleasant reading corner seat; slight wear from everyday use.',
  ),
  item(
    'notebook',
    'guest',
    'Notebook and fountain pen set',
    'A notebook and fountain pen for handwritten plans, sketches, and travel notes. Includes both items as a single stationery bundle.',
    ['notebook', 'fountainpen'],
    'like_new',
  ),
  item(
    'skateboard',
    'guest',
    'Neighbourhood skateboard',
    'A used skateboard with a characterful deck. Cosmetic scratches; please inspect wheels and bearings before use.',
    ['skateboard'],
    'fair',
  ),
  item(
    'ceramics',
    'lea',
    'Blue ceramic tableware',
    'A small mixed tableware set in soft blue tones. Plates and bowls included; light surface marks and no deliberately hidden damage.',
  ),
  item(
    'mug',
    'lea',
    'Favourite morning mug',
    'A ceramic mug ready for another kitchen. Clean and gently used, with a simple everyday shape.',
  ),
  item(
    'plants',
    'lea',
    'Two little balcony succulents',
    'A succulent and a cactus, each with its pot. Offered as a pair for a bright windowsill or sheltered balcony.',
    ['plants', 'cactus'],
  ),
  item(
    'polaroid',
    'noah',
    'Instant camera',
    'A cheerful instant camera for analogue experiments. Film is not included; the pictured camera is illustrative.',
  ),
  item(
    'lens',
    'noah',
    'Camera zoom lens',
    'A zoom lens from a photography hobby. Check mount compatibility before proposing a real swap; this demo does not assert a particular mount.',
  ),
  item(
    'chess',
    'ines',
    'Classic chess pieces',
    'A complete fictional chess set for quiet games at home. Pieces are well cared for; suitable for a casual player.',
  ),
  item(
    'boardgame',
    'ines',
    'Settlers-style board game',
    'A strategy board game for a small group of friends. This fictional set has its playing pieces and rules; the box shows light wear.',
  ),
  item(
    'woodenchair',
    'hugo',
    'Wooden dining chair',
    'A simple wooden chair with a comfortable back. A few visible marks give it character; useful as an extra seat.',
  ),
  item(
    'lamp',
    'hugo',
    'Adjustable desk lamp',
    'A dark metal task lamp for reading or working. Clean finish with a few small signs of use.',
  ),
  item(
    'kettle',
    'hugo',
    'Stovetop kettle',
    'A traditional metal kettle with a handle. Cleaned and ready for a kitchen that prefers a slower morning routine.',
    ['kettle'],
    'fair',
  ),
  item(
    'bag',
    'sarah',
    'Everyday shoulder bag',
    'A structured handbag with room for small daily essentials. Gently used, with light wear on the handles.',
  ),
  item(
    'perfume',
    'sarah',
    'Decorative fragrance bottle',
    'An empty fragrance bottle, offered for display or a creative upcycling project. No cosmetic product is included.',
  ),
  item(
    'jacket',
    'sarah',
    'Weekend jacket',
    'A casual jacket for layering. Clean and cared for; check fit with the owner before arranging a real exchange.',
  ),
  item(
    'watch',
    'adam',
    'Classic wristwatch',
    'A watch with a traditional dial and strap. An everyday accessory with gentle signs of wear.',
  ),
  item(
    'sneakers',
    'adam',
    'Red trainers',
    'Bright red trainers with clean uppers and light sole wear. Ask about sizing before a real exchange.',
  ),
  item(
    'shoes',
    'adam',
    'Walking shoes',
    'A pair of everyday shoes for city walks. Normal wear, cleaned before listing; sizing can be discussed.',
  ),
  item(
    'rucksack',
    'maya',
    'Green hiking rucksack',
    'A roomy green pack with multiple straps and pockets. Used on gentle weekend trails, with honest cosmetic wear.',
  ),
  item(
    'fountainpen',
    'maya',
    'Fountain pen',
    'A pen for slow handwritten notes. Offered without an ink supply, ready for someone who enjoys putting words on paper.',
  ),
  item(
    'vintagebooks',
    'eli',
    'Vintage book collection',
    'A characterful bundle of old books. Worn covers and yellowed pages are part of their story. Offered together.',
    ['vintagebooks'],
    'fair',
  ),
  item(
    'poetrybook',
    'eli',
    'Poetry for a quiet afternoon',
    'A slim poetry book for reading in small moments. Clean inside, with slight shelf wear on the cover.',
  ),
  item(
    'vinyl',
    'zoe',
    'Vinyl record for your collection',
    'A vinyl record from a much-loved collection. Sleeve and playable record included in this fictional listing; no specific artist is promised.',
  ),
  item(
    'keyboard',
    'zoe',
    'Compact desktop keyboard',
    'A tidy keyboard for a simple desk setup. Clean keys and a slim profile; connection compatibility can be discussed.',
  ),
];

export const swaps = [
  {
    key: 'incoming-camera',
    creator: 'noah',
    items: ['camera', 'polaroid'],
    status: 'proposed',
    coffee: 'pending',
    meeting: 'proposed',
  },
  {
    key: 'outgoing-music',
    creator: 'guest',
    items: ['headphones', 'keyboard'],
    status: 'proposed',
  },
  {
    key: 'confirmed-plants',
    creator: 'guest',
    items: ['cactus', 'plants'],
    status: 'confirmed',
    coffee: 'accepted',
    meeting: 'confirmed',
  },
  {
    key: 'completed-books',
    creator: 'eli',
    items: ['books', 'vintagebooks'],
    status: 'completed',
  },
  {
    key: 'cancelled-guitar',
    creator: 'guest',
    items: ['guitar', 'perfume'],
    status: 'cancelled',
  },
  {
    key: 'group-weekend',
    creator: 'guest',
    items: ['backpack', 'chess', 'rucksack'],
    status: 'confirmed',
    meeting: 'confirmed',
    chat: 'accepted',
  },
  {
    key: 'group-writing',
    creator: 'guest',
    items: ['notebook', 'fountainpen', 'poetrybook'],
    status: 'proposed',
    chat: 'accepted',
  },
  {
    key: 'group-invitation',
    creator: 'hugo',
    items: ['chair', 'ceramics', 'woodenchair'],
    status: 'proposed',
    chat: 'pending',
  },
  {
    key: 'disputed-bicycle',
    creator: 'guest',
    items: ['bicycle', 'shoes'],
    status: 'disputed',
  },
] as const;
